<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>8cead553-c87b-4d92-888d-168f9a616588</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CQRS.Infrastructure\StreamVibe.Infrastructure.csproj" />
  </ItemGroup>

</Project>
