<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CQRS.Domain\StreamVibe.Domain.csproj" />
  </ItemGroup>
</Project>
